name: uguard_app
description: UGuard Safety Application
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.12.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  http: ^0.13.3
  provider: ^6.0.1
  path: ^1.8.0
  google_maps_flutter_web: ^0.3.2
  google_maps_flutter: ^2.0.9
  shared_preferences: ^2.0.7
  json_serializable: ^4.1.4
  firebase_auth: ^3.2.0
  image_picker: ^0.8.4+1
  path_provider: ^2.0.4
  location: ^4.3.0
  geolocator: ^7.7.1
  permission_handler: ^8.1.6
  intl: ^0.17.0
  firebase_database: ^8.1.0
  firebase_database_web: ^0.1.1
  fluttertoast: ^8.0.8
  geocoding: ^2.0.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.1
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  flutter_local_notifications: ^9.1.4
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  url_launcher: ^6.0.2
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  photo_view: ^0.12.0
  video_player: ^2.1.12
  flutter_facebook_auth: ^3.5.0
  flutter_sound: ^8.2.5
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  the_apple_sign_in: ^1.1.1
  video_thumbnail: ^0.4.3
  bloc: ^8.0.1
  onesignal_flutter: ^3.2.7
  flutter_bloc: ^8.0.0
  material_floating_search_bar: ^0.3.6
  
 

 

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/uguard.png