name: flutter_listings
description: A new Listings Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  shared_preferences: ^2.0.6
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  image_picker: ^0.8.2
  firebase_storage: ^10.0.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  provider: ^5.0.0
  url_launcher: ^6.0.2
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  video_thumbnail: ^0.3.3
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  video_player: ^2.1.12
  flutter_facebook_auth: ^3.5.0
  http: ^0.13.3
  geolocator: ^7.3.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  firebase_messaging: ^10.0.4
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  in_app_purchase: ^1.0.6
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_staggered_grid_view: ^0.4.0
  google_mobile_ads: ^0.13.2
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.0
  flutter_sound: ^8.2.5
  visibility_detector: ^0.2.0
  easy_localization: ^3.0.0
  the_apple_sign_in: ^1.1.1
  permission_handler: ^8.1.4+2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dependency_overrides:
  flutter_google_places:
    git:
      url: https://github.com/hoc081098/flutter_google_places.git
      ref: 7b6c2aa2053131142c0e48639823d24f312d00c1

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/real_estate.png'

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

