name: instachatty
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.13.4 <3.0.0'
dependencies:
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  image_picker: ^0.8.2
  firebase_storage: ^10.0.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  provider: ^5.0.0
  url_launcher: ^6.0.2
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  video_thumbnail: ^0.3.3
  path_provider: ^2.0.2
  photo_view: ^0.12.0
  video_player: ^2.1.12
  flutter_facebook_auth: ^3.5.0
  http: ^0.13.3
  firebase_messaging: ^10.0.4
  flutter_sound: ^8.2.5
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  the_apple_sign_in: ^1.1.1
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf

    - family: sanFran
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf