name: uguard_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.1
  path: ^1.8.0
  google_maps_flutter_web: ^0.3.2
  google_maps_flutter: ^2.0.9
  shared_preferences: ^2.0.7
  firebase_auth: ^3.2.0
  image_picker: ^0.8.4+1
  path_provider: ^2.0.4
  location: ^4.3.0
  geolocator: ^8.0.0
  permission_handler: ^8.1.6
  firebase_database: ^8.1.0
  firebase_database_web: ^0.1.1
  geocoding: ^2.0.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.1
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  flutter_local_notifications: ^9.1.4
  camera: ^0.9.4+5  
  image_cropper: ^1.4.1
  equatable: ^2.0.3
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  dio: ^4.0.4
  sqflite: ^2.0.0+4
  fluttertoast: ^8.0.8
  flutter_sound: ^8.4.2
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git  
  url_launcher: ^6.0.2
  flutter_native_image: ^0.0.6+1   
  video_compress: ^3.1.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  #video_thumbnail: ^0.4.3  
  photo_view: ^0.12.0
  video_player: ^2.1.12
  flutter_facebook_auth: ^3.5.0 
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0 
  easy_localization: ^3.0.0  
  the_apple_sign_in: ^1.1.1
  video_thumbnail: ^0.4.3
 


dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/logo.png'
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/uGuard2.png
    - assets/images/top1.png
    - assets/images/top2.png
    - assets/images/bottom1.png
    - assets/images/bottom2.png
    - assets/images/uGuard.png
    - assets/images/safeUpic.jpg
    - assets/images/darkredbottom2.png
    - assets/images/darkredtop2.png
    - assets/images/blackbottom2.png
    - assets/images/blacktop2.png
    - assets/images/graybottom2.png
    - assets/images/graytop2.png
    - assets/images/lightredbottom2.png
    - assets/images/lightredtop2.png
    - assets/images/redbottom1.png
    - assets/images/redtop1.png
    - assets/images/blendlightredbottom2.png
    - assets/images/redwaves.jpeg
    - assets/images/redwavestop.jpeg
    - assets/images/homepagewaves.jpeg
    - assets/images/registerbgimage.jpeg
    - assets/images/resetbgimage.jpeg
    - assets/locations.json
    - assets/images/user_icon.png
    - assets/images/uGuardSmall.png
    - assets/images/uGuardBitMap.png
    - assets/images/message_icon.png
    - assets/images/
    - assets/translations/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: ChanceryCursive
      fonts: 
        - asset: assets/fonts/ChanceryCursive-dxD6.ttf
          weight: 700
    - family: HelloKetta
      fonts:
        - asset: assets/fonts/HelloKetta-d99oX.ttf
          weight: 700
    - family: CandyCaneRegular
      fonts:
        - asset: assets/fonts/CandyCaneRegular-WyaPv.ttf
          weight: 700
    - family: WhoaSaucePersonalUseBold
      fonts: 
        - asset: assets/fonts/WhoaSaucePersonalUseBold-mLmV5.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
